### ISSUE TITLE
A_CONST and NULL/empty string

### ISSUE THREAD

**Issue by zhm** [lfittl/libpg_query#3]
These 2 queries output the exact same tree:

```
SELECT ''
```

```
SELECT NULL
```

I think there is a bug in the handling of `A_CONST` with empty string values.

Here is the output for reference:

https://gist.github.com/zhm/715a15c1b4d89a6d9807

**Comment by zhm** [comment]
I actually think I see the bug here https://github.com/lfittl/libpg_query/blob/master/patches/01_output_nodes_as_json.patch#L145

But I'm not sure if it's intentional to handle another case.

**Comment by lfittl** [comment]
I think you are right that it should return an empty string - I'll make that change, wanted to re-arrange something with that patch anyway :)

**Comment by lfittl** [comment]
I'll close this since you fixed it in #5 :tada:
